title: Programming for Humans
author: 
    name: Anthony Moniz
    email: anthony.moniz.g@gmail.com
description: >
    My personal blog. Hoping to share what it means to work well in the games industry, in a team, and as a programmer.

# Build settings
theme: minima
        
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-admin

sass:
  quiet_deps: true
  silence_deprecations: [import]

minima:
# Minima skin selection. Available skins are:
  #   Available skins:
  #     * classic            Default, light color scheme.
  #     * dark               Dark variant of the classic skin.
  #     * auto               Adaptive skin based on the default classic and dark skins.
  #     * solarized-light    Light variant of solarized color scheme.
  #     * solarized-dark     Dark variant of solarized color scheme.
  #     * solarized          Adaptive skin for solarized color scheme skins.
  skin: solarized-dark
  
  # Specific pages for site navigation.
  #   If you wish to link only specific pages in the site-navigation, use this and list
  #   the `path` property (as represented via Liquid) of the pages in the order they
  #   should be rendered.
  nav_pages:
    - about.md
  
  # Minima date format.
  #   The default value is "%b %d, %Y" (e.g. Nov 14, 2023).
  #   Refer to https://shopify.github.io/liquid/filters/date/ for valid values.
  # date_format: "%b-%d-%Y"
  
  # Set to `true` to show excerpts on the homepage.
  show_excerpts: true
  
  # Social Media Links
  #   Renders icons via Font Awesome Free webfonts CDN, based on ordered list of entries.
  #   Entry keys:
  #     * title    Tooltip rendered on hovering over icon.
  #     * icon     Font Awesome icon id. `github` corresponds to `fa-github`.
  #     * url      Full URL of social profile.
  social_links:
  #  - title: Minima Theme repository at GitHub
  #    icon: github
  #    url: "https://github.com/jekyll/minima"
  #  - title: Jekyll at X (formerly Twitter)
  #    icon: x-twitter
  #    url: "https://x.com/jekyllrb"
  
#social links:
github_username: Moniz
rss: rss
  
# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html
collections:
    #the name of a collection. Maps to a folder _authors
    authors:
        output: true
        
defaults:
    - scope:
        path: ""
        type: "authors"
      values:
        layout: "author"
    - scope:
        path: ""
        type: "posts"
      values:
        layout: "post"
    - scope:
        path: ""
      values:
        layout: "default"